# Generated by Django 4.2.2 on 2023-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=4)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('insight', models.TextField()),
                ('url', models.URLField()),
                ('region', models.CharField(blank=True, max_length=255)),
                ('start_year', models.CharField(blank=True, max_length=4)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('add_date', models.DateTimeField()),
                ('publish_date', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=255)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('likelihood', models.IntegerField()),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'datum',
                'db_table': 'data',
                'managed': True,
            },
        ),
    ]
